---
title: "Integrated scRNA-seq"
output: html_document
date: "2022-10-07"
---

```{r}
#Load packages 
library(Seurat)
library(SeuratData)
library(patchwork)
library(tidyverse)

#Load dataset
#Jansky 
Jansky_adrenal <- readRDS("~/Integrated (Jansky & Aadameyko)/Jansky_adrenal.RDS")
#Adameyko
Adameyko_adrenal <- readRDS("~/Integrated (Jansky & Aadameyko)/Adameyko_adrenal.rds")

#Integrate Jansky & Adameyko dataset
#[[1]] is Adameyko dataset
#[[2]] is Jansky dataset
Integraed <- list(Adameyko_adrenal, Jansky_adrenal)

#Normalize and identify variable features for each dataset independently
Integraed <- lapply(X = Integraed, FUN = function(x) {
    x <- NormalizeData(x)
    x <- FindVariableFeatures(x, selection.method = "vst", nfeatures = 2000)
})

#Select features that are repeatedly variable across datasets for integration
features <- SelectIntegrationFeatures(object.list = Integraed)
features %>% unique()

```

##Perform integration

```{r}
Integrated.anchors <- FindIntegrationAnchors(object.list = Integraed, anchor.features = features)

#Create integrated data assay
Integrated.assay <- IntegrateData(anchorset = Integrated.anchors)
DefaultAssay(Integrated.assay) <- "integrated"

# Run the standard workflow for visualization and clustering
Integrated.assay <- ScaleData(Integrated.assay, verbose = FALSE)
Integrated.assay <- RunPCA(Integrated.assay, npcs = 30, verbose = FALSE)
Integrated.assay <- RunUMAP(Integrated.assay, reduction = "pca", dims = 1:30)
Integrated.assay <- FindNeighbors(Integrated.assay, reduction = "pca", dims = 1:30)
Integrated.assay <- FindClusters(Integrated.assay, resolution = 0.5)

#Make DimPlot 
p1 <- DimPlot(Integrated.assay, reduction = "umap", group.by = "fate")
p1
p2 <- DimPlot(Integrated.assay, reduction = "umap", label = TRUE, repel = TRUE)
p1 + p2
```
